site_name: Alternatives
copyright: Copyright 2022 MicrocontrollersDev

theme:
  favicon: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.annotate
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: purple
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

repo_name: Alternatives
repo_url: https://github.com/MicrocontrollersDev/Alternatives
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MicrocontrollersDev/Alternatives
    - icon: fontawesome/brands/discord
      link: https://inv.wtf/micro

nav:
  - "Home": "index.md"
  - "Contributors": "contributors.md"
  - "Latest":
      - "OptiFine": "latest/optifine.md"
      - "Lunar Client": "latest/lunar_client.md"
  - "1.12.2":
      - "Feather Client": "1.12.2/feather_client.md"
  - "1.8.9":
      - "HyChat": "1.8.9/hychat.md"
      - "5zig": "1.8.9/5zig.md"
      - "Refraction v4": "1.8.9/refraction_v4.md"
      - "Badlion Client": "1.8.9/badlion_client.md"
      - "Feather Client": "1.8.9/feather_client.md"
      - "LabyMod": "1.8.9/labymod.md"
      - "Lunar Client": "1.8.9/lunar_client.md"
      - "Wyvtils": "1.8.9/wyvtils.md"
      - "Danker's Skyblock Mod": "1.8.9/dsm.md"
      - "SkyblockCatia": "1.8.9/skyblockcatia.md"
      - "SkyblockExtras": "1.8.9/skyblockextras.md"
      - "Dungeon Utilities": "1.8.9/dungeon_utilities.md"
      - "Skyblock Reinvented": "1.8.9/skyblock_reinvented.md"
      - "Skypixel": "1.8.9/skypixel.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
